# Generated by Django 4.2.2 on 2023-06-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('id_sensor', models.TextField()),
                ('Timestamp', models.DateTimeField()),
                ('Temperatura', models.FloatField()),
                ('Humedad', models.FloatField()),
                ('CO2', models.FloatField()),
                ('Ocupacion', models.FloatField()),
                ('Icl', models.FloatField()),
                ('IDA', models.TextField()),
                ('temperatura_radiante_trs', models.FloatField(db_column='Temperatura Radiante TRS')),
                ('temperatura_radiante_try', models.FloatField(db_column='Temperatura Radiante TRY')),
                ('temperatura_radiante_itrc', models.FloatField(db_column='Temperatura Radiante ITRC')),
                ('pmv', models.FloatField()),
                ('ppd', models.FloatField()),
                ('Categoria', models.TextField()),
                ('Estrellas', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Data_sensores',
            },
        ),
    ]
